package com.sanyo.quote.domain;
// default package
// Generated Sep 9, 2013 12:56:17 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
/**
 * ThkUser generated by hbm2java
 */
@Entity
@Table(name = "sy_user", catalog = "sanyo")
public class User implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "userid", unique = true, nullable = false)
	private Integer userid;
	
	@Column(name = "usercode", length = 45)
	private String usercode;
	
	@Column(name = "username", length = 30,unique = true, nullable = false)
	private String username;
	
	@Column(name = "password", length = 45)
	private String password;
	
	@Column(name = "email", length = 30)
	private String email;
	
	@Column(name = "mobile", length = 15)
	private String mobile;
	
	@Column(name = "avatar", length = 45)
	private String avatar;
	
	@Column(name = "description", length = 1028)
	private String description;
	
	@Column(name = "active")
	private Boolean active;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", length = 0)
	private Date updated;
	
	@Column(name = "updatedby")
	private Integer updatedby;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 0)
	private Date created;
	
	@Column(name = "createdby")
	private Integer createdby;
	
	@ManyToMany(cascade = CascadeType.ALL,fetch = FetchType.EAGER)
	@JoinTable(name="user_group", joinColumns={@JoinColumn(name="userid")}
			, inverseJoinColumns={@JoinColumn(name="groupid")})
	private List<Group> grouplist;

	public List<Group> getGrouplist() {
		return grouplist;
	}

	public void setGrouplist(List<Group> grouplist) {
		this.grouplist = grouplist;
	}

	public User() {
	}

	public User(String usercode, String username, String password,
			String email, String mobile, String avatar, String description,
			Boolean active, Date updated, Integer updatedby,
			Date created, Integer createdby) {
		this.usercode = usercode;
		this.username = username;
		this.password = password;
		this.email = email;
		this.mobile = mobile;
		this.avatar = avatar;
		this.description = description;
		this.active = active;
		this.updated = updated;
		this.updatedby = updatedby;
		this.created = created;
		this.createdby = createdby;
	}


	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	
	public String getUsercode() {
		return this.usercode;
	}

	public void setUsercode(String usercode) {
		this.usercode = usercode;
	}

	
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	
	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}


	
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}


	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	
	public Integer getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}

	
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	
	public Integer getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}
	
}
